targetScope = 'subscription'

// ------------------
//    IMPORTS
// ------------------
import * as my from '_modules/exports.bicep'

// ------------------
//    PARAMETERS
// ------------------

@description('The name of the workload, used in the naming scheme of the module resources')
param workloadName my.nonEmptyStringType

@description('The name of the shared workload, used in the naming scheme of the module resources')
param sharedWorkloadName my.nonEmptyStringType

@allowed([
  'prod'
  'qa'
])
@description('Environment abbreviation used in the naming scheme of the module resources')
param env string 

@description('The selected region of the resources')
param location string = deployment().location

@description('Configuration settings for the APIM VNet')
param vnetSharedConfiguration my.vnetSettingsType

@description('Configuration settings for the APIM')
param apimConfiguration my.apimSettingsType

@description('Configuration settings for the Spoke VNet')
param vnetSpokeConfiguration my.vnetSettingsType


// ------------------
// VARIABLES
// ------------------



// ------------------
// RESOURCES
// ------------------

module sharedDeployment './shared/deploy-shared.bicep' = {
  name: take('sharedDeployment-${deployment().name}', 64)  
  scope: subscription()
  params: {
    workloadName: sharedWorkloadName
    env: env
    location: location
    vnetSharedConfiguration: vnetSharedConfiguration
    apimConfiguration: apimConfiguration
  }
}

module spokeAppResources './spoke/deploy-spoke.bicep' = {
  name: take('spokeDeployment-${deployment().name}', 64)  
  scope: subscription()
  params: {
    workloadName: workloadName
    env: env
    location: location
    vnetSpokeConfiguration: vnetSpokeConfiguration
    //TODO: Discuss if we need to pass the vnetHubResourceId to the spoke module
    vnetHubResourceId: sharedDeployment.outputs.vnetSharedResourceId
    keyvaultPrivateDnsZoneId: sharedDeployment.outputs.keyvaultPrivateDnsZoneId
    functionAppPrivateDnsZoneId: sharedDeployment.outputs.functionAppPrivateDnsZoneId
    cosmosDbPrivateDnsZoneId: sharedDeployment.outputs.cosmosDbPrivateDnsZoneId
  }
}

// ------------------
// OUTPUTS
// ------------------
@description('Resource name of the newly created APIM')
output apimName string = sharedDeployment.outputs.apimName

@description('Resource id of the newly created APIM')
output apimId string = sharedDeployment.outputs.apimId

@description('The id of the Keyvault')
output keyvaultId string = spokeAppResources.outputs.keyvaultId

@description('The name of the Keyvault')
output keyvaultName string = spokeAppResources.outputs.keyvaultName

@description('The id of the staticWebApp')
output staticWebAppId string = spokeAppResources.outputs.staticWebAppId

@description('The name of the staticWebApp')
output staticWebAppName string = spokeAppResources.outputs.staticWebAppName

@description('The default autogenerated hostname for the static site.')
output staticWebAppDefaultHostname string = spokeAppResources.outputs.staticWebAppDefaultHostname
